/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PromoCodesRouteImport } from './routes/promo-codes'
import { Route as PayoutsRouteImport } from './routes/payouts'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropFirmsIndexRouteImport } from './routes/prop-firms.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PropFirmsSlugRouteImport } from './routes/prop-firms.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminBlogsRouteImport } from './routes/admin.blogs'
import { Route as ApiAiGenerateBlogRouteImport } from './routes/api/ai/generate-blog'
import { Route as ApiPublicCronAutoBlogRouteImport } from './routes/api/public/cron/auto-blog'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoCodesRoute = PromoCodesRouteImport.update({
  id: '/promo-codes',
  path: '/promo-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const PayoutsRoute = PayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropFirmsIndexRoute = PropFirmsIndexRouteImport.update({
  id: '/prop-firms/',
  path: '/prop-firms/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropFirmsSlugRoute = PropFirmsSlugRouteImport.update({
  id: '/prop-firms/$slug',
  path: '/prop-firms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/admin/blogs',
  path: '/admin/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiGenerateBlogRoute = ApiAiGenerateBlogRouteImport.update({
  id: '/api/ai/generate-blog',
  path: '/api/ai/generate-blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronAutoBlogRoute = ApiPublicCronAutoBlogRouteImport.update({
  id: '/api/public/cron/auto-blog',
  path: '/api/public/cron/auto-blog',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/payouts': typeof PayoutsRoute
  '/promo-codes': typeof PromoCodesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/prop-firms/$slug': typeof PropFirmsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/prop-firms/': typeof PropFirmsIndexRoute
  '/api/ai/generate-blog': typeof ApiAiGenerateBlogRoute
  '/api/public/cron/auto-blog': typeof ApiPublicCronAutoBlogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/payouts': typeof PayoutsRoute
  '/promo-codes': typeof PromoCodesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/prop-firms/$slug': typeof PropFirmsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/prop-firms': typeof PropFirmsIndexRoute
  '/api/ai/generate-blog': typeof ApiAiGenerateBlogRoute
  '/api/public/cron/auto-blog': typeof ApiPublicCronAutoBlogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/payouts': typeof PayoutsRoute
  '/promo-codes': typeof PromoCodesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/prop-firms/$slug': typeof PropFirmsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/prop-firms/': typeof PropFirmsIndexRoute
  '/api/ai/generate-blog': typeof ApiAiGenerateBlogRoute
  '/api/public/cron/auto-blog': typeof ApiPublicCronAutoBlogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/contact'
    | '/payouts'
    | '/promo-codes'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/admin/blogs'
    | '/blog/$slug'
    | '/category/$slug'
    | '/prop-firms/$slug'
    | '/admin/'
    | '/prop-firms/'
    | '/api/ai/generate-blog'
    | '/api/public/cron/auto-blog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/contact'
    | '/payouts'
    | '/promo-codes'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/admin/blogs'
    | '/blog/$slug'
    | '/category/$slug'
    | '/prop-firms/$slug'
    | '/admin'
    | '/prop-firms'
    | '/api/ai/generate-blog'
    | '/api/public/cron/auto-blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/contact'
    | '/payouts'
    | '/promo-codes'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/admin/blogs'
    | '/blog/$slug'
    | '/category/$slug'
    | '/prop-firms/$slug'
    | '/admin/'
    | '/prop-firms/'
    | '/api/ai/generate-blog'
    | '/api/public/cron/auto-blog'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  PayoutsRoute: typeof PayoutsRoute
  PromoCodesRoute: typeof PromoCodesRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminBlogsRoute: typeof AdminBlogsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CategorySlugRoute: typeof CategorySlugRoute
  PropFirmsSlugRoute: typeof PropFirmsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PropFirmsIndexRoute: typeof PropFirmsIndexRoute
  ApiAiGenerateBlogRoute: typeof ApiAiGenerateBlogRoute
  ApiPublicCronAutoBlogRoute: typeof ApiPublicCronAutoBlogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo-codes': {
      id: '/promo-codes'
      path: '/promo-codes'
      fullPath: '/promo-codes'
      preLoaderRoute: typeof PromoCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payouts': {
      id: '/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof PayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prop-firms/': {
      id: '/prop-firms/'
      path: '/prop-firms'
      fullPath: '/prop-firms/'
      preLoaderRoute: typeof PropFirmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prop-firms/$slug': {
      id: '/prop-firms/$slug'
      path: '/prop-firms/$slug'
      fullPath: '/prop-firms/$slug'
      preLoaderRoute: typeof PropFirmsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/admin/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/generate-blog': {
      id: '/api/ai/generate-blog'
      path: '/api/ai/generate-blog'
      fullPath: '/api/ai/generate-blog'
      preLoaderRoute: typeof ApiAiGenerateBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/auto-blog': {
      id: '/api/public/cron/auto-blog'
      path: '/api/public/cron/auto-blog'
      fullPath: '/api/public/cron/auto-blog'
      preLoaderRoute: typeof ApiPublicCronAutoBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  PayoutsRoute: PayoutsRoute,
  PromoCodesRoute: PromoCodesRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminBlogsRoute: AdminBlogsRoute,
  BlogSlugRoute: BlogSlugRoute,
  CategorySlugRoute: CategorySlugRoute,
  PropFirmsSlugRoute: PropFirmsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  PropFirmsIndexRoute: PropFirmsIndexRoute,
  ApiAiGenerateBlogRoute: ApiAiGenerateBlogRoute,
  ApiPublicCronAutoBlogRoute: ApiPublicCronAutoBlogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
